import {
  Info, HelpCircle, Link2, Download, Home, ExternalLink, Globe, Search,
  Settings, Star, Tag, Bookmark, Clock, Bell, Flag, ChevronRight,
  Share2, Eye, Check, AlertCircle, BadgeCheck, Rss, Megaphone, Pin,
  File, FileText, Folder, FolderOpen, FileCheck, FileSearch,
  FileSpreadsheet, FileCode, ClipboardList, ClipboardCheck, ClipboardEdit,
  ScrollText, Newspaper, Pencil, Pen, PenLine, Archive, Package, Layers,
  BookOpen, BookMarked, BookCopy, Library,
  GraduationCap, School, Award, Trophy, Medal,
  FlaskConical, Microscope, Calculator, Ruler, Lightbulb,
  Brain, Atom, Dna, TestTube, Sigma,
  Mail, MailOpen, MessageSquare, MessageCircle, Phone, PhoneCall,
  Video, Send, Inbox, AtSign, Contact,
  User, Users, UserCheck, UserPlus, UserCog,
  ShieldCheck, LockKeyhole, Key, Fingerprint, IdCard,
  Map, MapPin, Navigation, Compass, Bus, Car, Plane,
  Building, Building2, Landmark, Trees, TreePine,
  Database, LayoutDashboard, Monitor, Laptop, Tablet, Smartphone,
  PieChart, BarChart3, LineChart, TrendingUp, Table, Code, Terminal,
  QrCode, Printer, Server, Cpu, HardDrive, Wifi,
  CreditCard, Wallet, Receipt, Scale, Banknote, Coins, CircleDollarSign,
  Calendar, CalendarDays, CalendarCheck, CalendarClock,
  ListChecks, Timer, Hourglass,
  Image, Music, Heart, Stethoscope, Umbrella,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// [anahtar, bileşen, türkçe_arama_etiketleri]
export const ICON_ENTRIES: [string, LucideIcon, string[]][] = [
  // ── Genel & Navigasyon ─────────────────────────────────────────────────────
  ["info",             Info,             ["bilgi", "hakkında", "açıklama"]],
  ["question",         HelpCircle,       ["soru", "yardım", "destek", "sss", "faq"]],
  ["home",             Home,             ["ana sayfa", "anasayfa", "ev"]],
  ["link",             Link2,            ["bağlantı", "link", "url"]],
  ["external-link",    ExternalLink,     ["dış bağlantı", "yeni sekme"]],
  ["globe",            Globe,            ["dünya", "internet", "web", "site", "uluslararası"]],
  ["search",           Search,           ["arama", "ara", "bul", "sorgula"]],
  ["settings",         Settings,         ["ayarlar", "yapılandırma", "tercihler"]],
  ["star",             Star,             ["yıldız", "favori", "öne çıkan", "önemli"]],
  ["bookmark",         Bookmark,         ["yer imi", "kaydet", "işaretle"]],
  ["clock",            Clock,            ["saat", "zaman", "süre", "çalışma saati"]],
  ["bell",             Bell,             ["zil", "bildirim", "uyarı", "duyuru"]],
  ["flag",             Flag,             ["bayrak", "işaret", "türk bayrağı"]],
  ["share",            Share2,           ["paylaş", "paylaşım", "sosyal medya"]],
  ["eye",              Eye,              ["göz", "görüntüle", "önizleme", "bak"]],
  ["check",            Check,            ["onay", "tamam", "doğru", "tamamlandı"]],
  ["alert",            AlertCircle,      ["uyarı", "dikkat", "hata", "önemli"]],
  ["badge-check",      BadgeCheck,       ["rozet", "onaylı", "doğrulanmış", "akredite"]],
  ["chevron-right",    ChevronRight,     ["ok", "ileri", "devam", "yönlendir"]],
  ["tag",              Tag,              ["etiket", "kategori", "sınıflama"]],
  ["rss",              Rss,              ["rss", "haber akışı", "abone ol"]],
  ["megaphone",        Megaphone,        ["duyuru", "anons", "ilan", "kampanya"]],
  ["pin",              Pin,              ["pin", "sabit", "önemli not"]],

  // ── Dosya & Doküman ────────────────────────────────────────────────────────
  ["file",             File,             ["dosya", "belge", "doküman"]],
  ["file-text",        FileText,         ["metin dosyası", "doküman", "rapor", "belge"]],
  ["folder",           Folder,           ["klasör", "dizin", "kategori"]],
  ["folder-open",      FolderOpen,       ["açık klasör", "içerik", "dizin"]],
  ["file-check",       FileCheck,        ["onaylı dosya", "kontrol edildi", "tamamlandı"]],
  ["file-search",      FileSearch,       ["dosya ara", "doküman ara", "evrak tara"]],
  ["file-spreadsheet", FileSpreadsheet,  ["tablo", "excel", "hesap tablosu", "veri"]],
  ["file-code",        FileCode,         ["kod dosyası", "yazılım", "program"]],
  ["clipboard",        ClipboardList,    ["pano", "liste", "form", "başvuru formu"]],
  ["clipboard-check",  ClipboardCheck,   ["onaylı form", "kontrol listesi", "tamamlandı"]],
  ["clipboard-edit",   ClipboardEdit,    ["formu düzenle", "başvur", "kayıt"]],
  ["scroll",           ScrollText,       ["makale", "bildiri", "metin", "tüzük", "yönetmelik"]],
  ["newspaper",        Newspaper,        ["gazete", "haber", "duyuru", "bülten"]],
  ["pencil",           Pencil,           ["kalem", "düzenle", "yazı"]],
  ["pen",              Pen,              ["kalem", "imza", "imzala"]],
  ["pen-line",         PenLine,          ["düzenleme", "not al", "metin gir"]],
  ["archive",          Archive,          ["arşiv", "arşivle", "geçmiş", "eski kayıtlar"]],
  ["package",          Package,          ["paket", "materyal", "kaynak", "kit"]],
  ["layers",           Layers,           ["katmanlar", "çoklu içerik", "koleksiyon"]],

  // ── Kitap & Akademik ───────────────────────────────────────────────────────
  ["book",             BookOpen,         ["kitap", "ders", "okuma", "akademik", "yayın"]],
  ["book-marked",      BookMarked,       ["işaretli kitap", "ders notu", "kaynak"]],
  ["book-copy",        BookCopy,         ["kopya", "ders materyali", "çoğalt"]],
  ["library",          Library,          ["kütüphane", "kitaplık", "kaynak merkezi"]],
  ["graduation-cap",   GraduationCap,    ["mezuniyet", "öğrenci", "diploma", "eğitim", "akademi"]],
  ["school",           School,           ["okul", "eğitim", "kampüs", "fakülte"]],
  ["award",            Award,            ["ödül", "başarı", "sertifika", "burs", "derece"]],
  ["trophy",           Trophy,           ["kupa", "şampiyonluk", "birinci", "başarı"]],
  ["medal",            Medal,            ["madalya", "derece", "yarışma", "ödül"]],
  ["flask",            FlaskConical,     ["şişe", "deney", "laboratuvar", "kimya", "lab"]],
  ["microscope",       Microscope,       ["mikroskop", "biyoloji", "araştırma", "bilim"]],
  ["calculator",       Calculator,       ["hesap makinesi", "matematik", "hesaplama"]],
  ["ruler",            Ruler,            ["cetvel", "ölçüm", "mühendislik", "çizim"]],
  ["lightbulb",        Lightbulb,        ["fikir", "inovasyon", "araştırma", "proje"]],
  ["brain",            Brain,            ["beyin", "yapay zeka", "bilişsel bilim", "akıl"]],
  ["atom",             Atom,             ["atom", "fizik", "bilim", "fen"]],
  ["dna",              Dna,              ["dna", "genetik", "biyoloji", "moleküler"]],
  ["test-tube",        TestTube,         ["test tüpü", "deney", "analiz", "lab"]],
  ["sigma",            Sigma,            ["sigma", "toplam", "matematik", "istatistik", "formül"]],

  // ── İletişim ───────────────────────────────────────────────────────────────
  ["mail",             Mail,             ["e-posta", "mail", "mesaj", "iletişim"]],
  ["mail-open",        MailOpen,         ["açık mail", "okunmuş", "gelen kutusu"]],
  ["message",          MessageSquare,    ["mesaj", "yorum", "iletişim", "destek"]],
  ["message-circle",   MessageCircle,    ["sohbet", "chat", "tartışma"]],
  ["phone",            Phone,            ["telefon", "ara", "iletişim", "çağrı merkezi"]],
  ["phone-call",       PhoneCall,        ["aktif arama", "görüşme", "çağrı"]],
  ["video",            Video,            ["video", "toplantı", "webinar", "canlı yayın"]],
  ["send",             Send,             ["gönder", "ilet", "başvuru gönder"]],
  ["inbox",            Inbox,            ["gelen kutusu", "posta kutusu", "başvurular"]],
  ["at-sign",          AtSign,           ["e-posta adresi", "@", "iletişim bilgisi"]],
  ["contact",          Contact,          ["kişi", "iletişim rehberi", "personel"]],

  // ── Kullanıcı & Güvenlik ───────────────────────────────────────────────────
  ["user",             User,             ["kullanıcı", "kişi", "öğrenci", "personel"]],
  ["users",            Users,            ["kullanıcılar", "grup", "topluluk", "ekip", "bölüm"]],
  ["user-check",       UserCheck,        ["onaylı kullanıcı", "kayıtlı öğrenci", "kabul"]],
  ["user-plus",        UserPlus,         ["kayıt ol", "yeni öğrenci", "ekle"]],
  ["user-cog",         UserCog,          ["kullanıcı ayarları", "profil", "hesap"]],
  ["shield",           ShieldCheck,      ["güvenlik", "koruma", "onaylı", "akredite"]],
  ["lock",             LockKeyhole,      ["kilit", "şifre", "güvenli", "erişim kısıtlı"]],
  ["key",              Key,              ["anahtar", "erişim", "şifre", "giriş"]],
  ["fingerprint",      Fingerprint,      ["parmak izi", "kimlik", "biyometrik"]],
  ["id-card",          IdCard,           ["kimlik kartı", "öğrenci kartı", "personel kartı"]],

  // ── Konum & Kampüs ─────────────────────────────────────────────────────────
  ["map",              Map,              ["harita", "kampüs haritası", "konum"]],
  ["map-pin",          MapPin,           ["pin", "adres", "kampüs", "konum işareti"]],
  ["navigation",       Navigation,       ["navigasyon", "yol tarifi", "yön"]],
  ["compass",          Compass,          ["pusula", "yön", "keşfet"]],
  ["bus",              Bus,              ["otobüs", "ulaşım", "toplu taşıma", "servis"]],
  ["car",              Car,              ["araba", "araç", "park", "otopark"]],
  ["plane",            Plane,            ["uçak", "uluslararası", "havalimanı"]],
  ["building",         Building,         ["bina", "fakülte", "enstitü", "blok"]],
  ["building-2",       Building2,        ["ofis binası", "idari bina", "rektörlük"]],
  ["landmark",         Landmark,         ["tarihi yapı", "anıt", "simge", "amfi"]],
  ["trees",            Trees,            ["ağaçlar", "doğa", "kampüs ortamı"]],
  ["tree-pine",        TreePine,         ["çam", "orman", "park"]],

  // ── Teknoloji & Sistem ─────────────────────────────────────────────────────
  ["database",         Database,         ["veri tabanı", "veri", "sistem", "kayıt"]],
  ["dashboard",        LayoutDashboard,  ["panel", "kontrol paneli", "özet ekranı"]],
  ["monitor",          Monitor,          ["ekran", "bilgisayar", "masaüstü", "uzaktan erişim"]],
  ["laptop",           Laptop,           ["dizüstü", "bilgisayar"]],
  ["tablet",           Tablet,           ["tablet", "mobil cihaz"]],
  ["smartphone",       Smartphone,       ["telefon", "mobil", "akıllı telefon", "uygulama"]],
  ["pie-chart",        PieChart,         ["pasta grafik", "istatistik", "rapor", "oran"]],
  ["bar-chart",        BarChart3,        ["çubuk grafik", "istatistik", "karşılaştırma"]],
  ["line-chart",       LineChart,        ["çizgi grafik", "trend", "ilerleme"]],
  ["trending-up",      TrendingUp,       ["büyüme", "artış", "gelişme", "başarı trendi"]],
  ["table",            Table,            ["tablo", "veri tablosu", "ders programı"]],
  ["code",             Code,             ["kod", "yazılım", "programlama", "geliştirme"]],
  ["terminal",         Terminal,         ["terminal", "komut satırı", "yazılım"]],
  ["qr",               QrCode,           ["qr kod", "barkod", "tara", "hızlı erişim"]],
  ["printer",          Printer,          ["yazıcı", "yazdır", "belge basmak"]],
  ["server",           Server,           ["sunucu", "sistem", "altyapı", "hosting"]],
  ["cpu",              Cpu,              ["işlemci", "donanım", "teknoloji", "bilişim"]],
  ["hard-drive",       HardDrive,        ["disk", "depolama", "yedek", "dosya sistemi"]],
  ["wifi",             Wifi,             ["wifi", "internet", "kablosuz ağ", "bağlantı"]],

  // ── Mali & İdari ───────────────────────────────────────────────────────────
  ["credit-card",      CreditCard,       ["kredi kartı", "ödeme", "burs", "harç"]],
  ["wallet",           Wallet,           ["cüzdan", "ödeme", "bütçe"]],
  ["receipt",          Receipt,          ["makbuz", "dekont", "ödeme belgesi", "fiş"]],
  ["scale",            Scale,            ["terazi", "hukuk", "adalet", "yönetmelik"]],
  ["banknote",         Banknote,         ["para", "nakit", "burs", "ödeme", "destek"]],
  ["coins",            Coins,            ["bozuk para", "ücret", "öğrenim harcı"]],
  ["dollar",           CircleDollarSign, ["ücret", "fiyat", "maliyet", "burs miktarı"]],

  // ── Takvim & Planlama ──────────────────────────────────────────────────────
  ["calendar",         Calendar,         ["takvim", "tarih", "etkinlik", "program"]],
  ["calendar-days",    CalendarDays,     ["haftalık program", "ders takvimi", "plan"]],
  ["calendar-check",   CalendarCheck,    ["onaylı randevu", "ders takvimi", "sınav takvimi"]],
  ["calendar-clock",   CalendarClock,    ["tarih saat", "zamanlama", "sınav saati"]],
  ["list-checks",      ListChecks,       ["kontrol listesi", "yapılacaklar", "görev"]],
  ["timer",            Timer,            ["zamanlayıcı", "süre", "geri sayım", "sınav süresi"]],
  ["hourglass",        Hourglass,        ["kum saati", "bekleme", "süre", "son başvuru"]],

  // ── Medya & Diğer ──────────────────────────────────────────────────────────
  ["download",         Download,         ["indir", "indirme", "dosya indir", "al"]],
  ["image",            Image,            ["resim", "fotoğraf", "görsel", "galeri"]],
  ["music",            Music,            ["müzik", "konser", "kültür sanat", "etkinlik"]],
  ["heart",            Heart,            ["kalp", "favori", "sağlık", "beğeni"]],
  ["stethoscope",      Stethoscope,      ["stetoskop", "sağlık", "tıp", "hastane", "sağlık birimi"]],
  ["umbrella",         Umbrella,         ["şemsiye", "sigorta", "koruma", "güvence"]],
];

// Anahtar → bileşen map'i (render için)
export const ICON_MAP = Object.fromEntries(
  ICON_ENTRIES.map(([k, v]) => [k, v])
) as Record<string, LucideIcon>;

// Fallback ikon (bilinmeyen anahtar için)
export { ExternalLink as FallbackIcon } from "lucide-react";