import {
  // ── Genel & Navigasyon ───────────────────────────────────────────────
  InfoIcon,
  QuestionIcon,
  HouseIcon,
  LinkIcon,
  ArrowSquareOutIcon,
  GlobeIcon,
  MagnifyingGlassIcon,
  GearIcon,
  StarIcon,
  BookmarkSimpleIcon,
  ClockIcon,
  BellIcon,
  FlagIcon,
  ShareNetworkIcon,
  EyeIcon,
  CheckIcon,
  WarningCircleIcon,
  SealCheckIcon,
  CaretRightIcon,
  TagIcon,
  RssSimpleIcon,
  MegaphoneIcon,
  PushPinIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  FunnelSimpleIcon,
  ArrowsClockwiseIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  SignOutIcon,
  SignInIcon,
  DotsThreeIcon,
  ListIcon,
  XIcon,

  // ── Dosya & Doküman ──────────────────────────────────────────────────
  FileIcon,
  FileTextIcon,
  FolderIcon,
  FolderOpenIcon,
  CheckCircleIcon ,
  FileMagnifyingGlassIcon,
  FileXlsIcon,
  FileCodeIcon,
  ClipboardIcon,
  ClipboardTextIcon,
  ScrollIcon,
  NewspaperIcon,
  PencilIcon,
  PenIcon,
  PenNibIcon,
  ArchiveIcon,
  PackageIcon,
  StackIcon,
  FilePdfIcon,
  FileDocIcon,
  FilePptIcon,
  FileZipIcon,
  FileCsvIcon,
  FileImageIcon,
  FileVideoIcon,
  FileAudioIcon,
  NoteIcon,
  NotepadIcon,
  ArticleIcon,

  // ── Kitap & Akademik ─────────────────────────────────────────────────
  BookOpenIcon,
  BookBookmarkIcon,
  BooksIcon,
  GraduationCapIcon,
  StudentIcon,
  CertificateIcon,
  TrophyIcon,
  MedalIcon,
  FlaskIcon,
  MicroscopeIcon,
  CalculatorIcon,
  RulerIcon,
  LightbulbIcon,
  BrainIcon,
  AtomIcon,
  DnaIcon,
  TestTubeIcon,
  MathOperationsIcon,
  ChalkboardIcon,
  ChalkboardTeacherIcon,
  ExamIcon,
  PresentationIcon,
  BackpackIcon,
  PencilLineIcon,
  NotebookIcon,

  // ── İletişim ─────────────────────────────────────────────────────────
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ChatIcon ,
  ChatCircleIcon,
  PhoneIcon,
  PhoneCallIcon,
  VideoCameraIcon,
  PaperPlaneTiltIcon,
  TrayIcon,
  AtIcon,
  AddressBookIcon,
  ChatDotsIcon,
  ChatTextIcon,
  ChatsIcon,
  WhatsappLogoIcon,
  TelegramLogoIcon,

  // ── Kullanıcı & Güvenlik ─────────────────────────────────────────────
  UserIcon,
  UsersIcon,
  UserCheckIcon,
  UserPlusIcon,
  UserGearIcon,
  ShieldCheckIcon,
  LockKeyIcon,
  KeyIcon,
  FingerprintIcon,
  IdentificationCardIcon,
  UserCircleIcon,
  UserListIcon,
  UsersThreeIcon,
  UserFocusIcon,
  PasswordIcon,

  // ── Konum & Kampüs ──────────────────────────────────────────────────
  MapTrifoldIcon,
  MapPinIcon,
  NavigationArrowIcon,
  CompassIcon,
  BusIcon,
  CarIcon,
  AirplaneTiltIcon,
  BuildingsIcon,
  BuildingIcon,
  BankIcon,
  TreeIcon,
  ParkIcon,
  MapPinLineIcon,
  PathIcon,
  RoadHorizonIcon,
  TrainIcon,
  TaxiIcon,

  // ── Teknoloji & Sistem ───────────────────────────────────────────────
  DatabaseIcon,
  SquaresFourIcon,
  MonitorIcon,
  LaptopIcon,
  DeviceTabletIcon,
  DeviceMobileIcon,
  ChartPieIcon,
  ChartBarIcon,
  ChartLineIcon,
  TrendUpIcon,
  TableIcon,
  CodeIcon,
  TerminalIcon,
  QrCodeIcon,
  PrinterIcon,
  HardDrivesIcon,
  CpuIcon,
  HardDriveIcon,
  WifiHighIcon,
  CloudIcon,
  CloudArrowUpIcon,
  CloudArrowDownIcon,
  DesktopIcon,
  GitBranchIcon,
  RobotIcon,

  // ── Mali & İdari ─────────────────────────────────────────────────────
  CreditCardIcon,
  WalletIcon,
  ReceiptIcon,
  ScalesIcon,
  MoneyIcon,
  CoinsIcon,
  CurrencyDollarIcon,
  CurrencyEurIcon,
  CurrencyGbpIcon,
  HandshakeIcon,
  BriefcaseIcon,
  StampIcon,
  GavelIcon,

  // ── Takvim & Planlama ────────────────────────────────────────────────
  CalendarIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CalendarDotsIcon,
  CheckSquareIcon,
  TimerIcon,
  HourglassIcon,
  AlarmIcon,
  ClockCountdownIcon,
  ListChecksIcon,
  ListBulletsIcon,

  // ── Medya & Diğer ────────────────────────────────────────────────────
  DownloadSimpleIcon,
  UploadSimpleIcon,
  ImageIcon,
  MusicNoteIcon,
  HeartIcon,
  StethoscopeIcon,
  UmbrellaIcon,
  CameraIcon,
  PlayIcon,
  PauseIcon,
  SpeakerHighIcon,
  MicrophoneIcon,
  FilmSlateIcon,
  PaletteIcon,
  PaintBrushIcon,
  SparkleIcon,
  SunIcon,
  MoonIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  SmileyIcon,
  HandHeartIcon,
  FirstAidIcon,
  PillIcon,
  ThermometerIcon,
  WheelchairIcon,
  BabyIcon,
  HandsPrayingIcon,

  // ── Oklar & Yönlendirme ──────────────────────────────────────────────
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowsOutSimpleIcon,
  ArrowsInSimpleIcon,
  CaretDownIcon,
  CaretUpIcon,
  CaretLeftIcon,

  // ── Düzenleme & Eylem ────────────────────────────────────────────────
  TrashIcon,
  CopyIcon,
  PlusIcon,
  MinusIcon,
  EqualsIcon,
  PowerIcon,
  ExportIcon,
  FlagCheckeredIcon,
  LightningIcon,
  FireIcon,
  ConfettiIcon,
  ProhibitIcon,
  CircleNotchIcon,
  SpinnerGapIcon,
} from "@phosphor-icons/react/ssr";

import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

// [anahtar, bileşen, türkçe_arama_etiketleri]
export const ICON_ENTRIES: [string, PhosphorIcon, string[]][] = [
  // ── Genel & Navigasyon ─────────────────────────────────────────────────────
  ["info",             InfoIcon,              ["bilgi", "hakkında", "açıklama"]],
  ["question",         QuestionIcon,          ["soru", "yardım", "destek", "sss", "faq"]],
  ["home",             HouseIcon,             ["ana sayfa", "anasayfa", "ev"]],
  ["link",             LinkIcon,              ["bağlantı", "link", "url"]],
  ["external-link",    ArrowSquareOutIcon,    ["dış bağlantı", "yeni sekme"]],
  ["globe",            GlobeIcon,             ["dünya", "internet", "web", "site", "uluslararası"]],
  ["search",           MagnifyingGlassIcon,   ["arama", "ara", "bul", "sorgula"]],
  ["settings",         GearIcon,              ["ayarlar", "yapılandırma", "tercihler"]],
  ["star",             StarIcon,              ["yıldız", "favori", "öne çıkan", "önemli"]],
  ["bookmark",         BookmarkSimpleIcon,    ["yer imi", "kaydet", "işaretle"]],
  ["clock",            ClockIcon,             ["saat", "zaman", "süre", "çalışma saati"]],
  ["bell",             BellIcon,              ["zil", "bildirim", "uyarı", "duyuru"]],
  ["flag",             FlagIcon,              ["bayrak", "işaret", "türk bayrağı"]],
  ["share",            ShareNetworkIcon,      ["paylaş", "paylaşım", "sosyal medya"]],
  ["eye",              EyeIcon,               ["göz", "görüntüle", "önizleme", "bak"]],
  ["check",            CheckIcon,             ["onay", "tamam", "doğru", "tamamlandı"]],
  ["alert",            WarningCircleIcon,     ["uyarı", "dikkat", "hata", "önemli"]],
  ["badge-check",      SealCheckIcon,         ["rozet", "onaylı", "doğrulanmış", "akredite"]],
  ["chevron-right",    CaretRightIcon,        ["ok", "ileri", "devam", "yönlendir"]],
  ["tag",              TagIcon,               ["etiket", "kategori", "sınıflama"]],
  ["rss",              RssSimpleIcon,         ["rss", "haber akışı", "abone ol"]],
  ["megaphone",        MegaphoneIcon,         ["duyuru", "anons", "ilan", "kampanya"]],
  ["pin",              PushPinIcon,           ["pin", "sabit", "önemli not"]],
  ["sort-asc",         SortAscendingIcon,     ["sırala", "artan", "a-z"]],
  ["sort-desc",        SortDescendingIcon,    ["sırala", "azalan", "z-a"]],
  ["filter",           FunnelSimpleIcon,      ["filtre", "filtrele", "süz"]],
  ["refresh",          ArrowsClockwiseIcon,   ["yenile", "güncelle", "tekrar"]],
  ["arrow-right",      ArrowRightIcon,        ["sağ ok", "ileri", "devam"]],
  ["arrow-left",       ArrowLeftIcon,         ["sol ok", "geri", "dön"]],
  ["sign-out",         SignOutIcon,           ["çıkış", "oturumu kapat"]],
  ["sign-in",          SignInIcon,            ["giriş", "oturum aç"]],
  ["dots",             DotsThreeIcon,         ["üç nokta", "menü", "daha fazla"]],
  ["menu",             ListIcon,              ["menü", "hamburger", "liste"]],
  ["close",            XIcon,                 ["kapat", "çarpı", "iptal"]],

  // ── Dosya & Doküman ────────────────────────────────────────────────────────
  ["file",             FileIcon,              ["dosya", "belge", "doküman"]],
  ["file-text",        FileTextIcon,          ["metin dosyası", "doküman", "rapor", "belge"]],
  ["folder",           FolderIcon,            ["klasör", "dizin", "kategori"]],
  ["folder-open",      FolderOpenIcon,        ["açık klasör", "içerik", "dizin"]],
  ["file-check",       CheckCircleIcon ,         ["onaylı dosya", "kontrol edildi", "tamamlandı"]],
  ["file-search",      FileMagnifyingGlassIcon, ["dosya ara", "doküman ara", "evrak tara"]],
  ["file-spreadsheet", FileXlsIcon,           ["tablo", "excel", "hesap tablosu", "veri"]],
  ["file-code",        FileCodeIcon,          ["kod dosyası", "yazılım", "program"]],
  ["clipboard",        ClipboardIcon,         ["pano", "liste", "form", "başvuru formu"]],
  ["clipboard-edit",   ClipboardTextIcon,     ["formu düzenle", "başvur", "kayıt"]],
  ["scroll",           ScrollIcon,            ["makale", "bildiri", "metin", "tüzük", "yönetmelik"]],
  ["newspaper",        NewspaperIcon,         ["gazete", "haber", "duyuru", "bülten"]],
  ["pencil",           PencilIcon,            ["kalem", "düzenle", "yazı"]],
  ["pen",              PenIcon,               ["kalem", "imza", "imzala"]],
  ["pen-nib",          PenNibIcon,            ["düzenleme", "not al", "metin gir", "tasarım"]],
  ["archive",          ArchiveIcon,           ["arşiv", "arşivle", "geçmiş", "eski kayıtlar"]],
  ["package",          PackageIcon,           ["paket", "materyal", "kaynak", "kit"]],
  ["layers",           StackIcon,             ["katmanlar", "çoklu içerik", "koleksiyon"]],
  ["file-pdf",         FilePdfIcon,           ["pdf", "belge", "doküman"]],
  ["file-doc",         FileDocIcon,           ["word", "belge", "doküman"]],
  ["file-ppt",         FilePptIcon,           ["sunum", "prezentasyon", "slayt"]],
  ["file-zip",         FileZipIcon,           ["sıkıştırılmış", "arşiv", "zip"]],
  ["file-csv",         FileCsvIcon,           ["csv", "veri", "tablo"]],
  ["file-image",       FileImageIcon,         ["görsel dosya", "resim dosyası"]],
  ["file-video",       FileVideoIcon,         ["video dosyası", "medya"]],
  ["file-audio",       FileAudioIcon,         ["ses dosyası", "podcast"]],
  ["note",             NoteIcon,              ["not", "hatırlatma", "memo"]],
  ["notepad",          NotepadIcon,           ["not defteri", "notlar", "memo"]],
  ["article",          ArticleIcon,           ["makale", "yazı", "blog"]],

  // ── Kitap & Akademik ───────────────────────────────────────────────────────
  ["book",             BookOpenIcon,          ["kitap", "ders", "okuma", "akademik", "yayın"]],
  ["book-marked",      BookBookmarkIcon,      ["işaretli kitap", "ders notu", "kaynak"]],
  ["books",            BooksIcon,             ["kitaplar", "kütüphane", "koleksiyon"]],
  ["library",          BooksIcon,             ["kütüphane", "kitaplık", "kaynak merkezi"]],
  ["graduation-cap",   GraduationCapIcon,     ["mezuniyet", "öğrenci", "diploma", "eğitim", "akademi"]],
  ["student",          StudentIcon,           ["öğrenci", "talebe", "eğitim"]],
  ["school",           ChalkboardTeacherIcon, ["okul", "eğitim", "kampüs", "fakülte"]],
  ["award",            CertificateIcon,       ["ödül", "başarı", "sertifika", "burs", "derece"]],
  ["trophy",           TrophyIcon,            ["kupa", "şampiyonluk", "birinci", "başarı"]],
  ["medal",            MedalIcon,             ["madalya", "derece", "yarışma", "ödül"]],
  ["flask",            FlaskIcon,             ["şişe", "deney", "laboratuvar", "kimya", "lab"]],
  ["microscope",       MicroscopeIcon,        ["mikroskop", "biyoloji", "araştırma", "bilim"]],
  ["calculator",       CalculatorIcon,        ["hesap makinesi", "matematik", "hesaplama"]],
  ["ruler",            RulerIcon,             ["cetvel", "ölçüm", "mühendislik", "çizim"]],
  ["lightbulb",        LightbulbIcon,         ["fikir", "inovasyon", "araştırma", "proje"]],
  ["brain",            BrainIcon,             ["beyin", "yapay zeka", "bilişsel bilim", "akıl"]],
  ["atom",             AtomIcon,              ["atom", "fizik", "bilim", "fen"]],
  ["dna",              DnaIcon,               ["dna", "genetik", "biyoloji", "moleküler"]],
  ["test-tube",        TestTubeIcon,          ["test tüpü", "deney", "analiz", "lab"]],
  ["math",             MathOperationsIcon,    ["matematik", "toplam", "formül", "istatistik"]],
  ["chalkboard",       ChalkboardIcon,        ["tahta", "kara tahta", "ders"]],
  ["teacher",          ChalkboardTeacherIcon, ["öğretmen", "hoca", "eğitmen"]],
  ["exam",             ExamIcon,              ["sınav", "test", "değerlendirme"]],
  ["presentation",     PresentationIcon,      ["sunum", "prezentasyon", "seminer"]],
  ["backpack",         BackpackIcon,          ["çanta", "sırt çantası", "öğrenci"]],
  ["pencil-line",      PencilLineIcon,        ["yazı yaz", "düzenle", "not al"]],
  ["notebook",         NotebookIcon,          ["defter", "not defteri", "kayıt"]],

  // ── İletişim ───────────────────────────────────────────────────────────────
  ["mail",             EnvelopeIcon,          ["e-posta", "mail", "mesaj", "iletişim"]],
  ["mail-open",        EnvelopeOpenIcon,      ["açık mail", "okunmuş", "gelen kutusu"]],
  ["message",          ChatIcon ,        ["mesaj", "yorum", "iletişim", "destek"]],
  ["message-circle",   ChatCircleIcon,        ["sohbet", "chat", "tartışma"]],
  ["phone",            PhoneIcon,             ["telefon", "ara", "iletişim", "çağrı merkezi"]],
  ["phone-call",       PhoneCallIcon,         ["aktif arama", "görüşme", "çağrı"]],
  ["video",            VideoCameraIcon,       ["video", "toplantı", "webinar", "canlı yayın"]],
  ["send",             PaperPlaneTiltIcon,    ["gönder", "ilet", "başvuru gönder"]],
  ["inbox",            TrayIcon,              ["gelen kutusu", "posta kutusu", "başvurular"]],
  ["at-sign",          AtIcon,                ["e-posta adresi", "@", "iletişim bilgisi"]],
  ["contact",          AddressBookIcon,       ["kişi", "iletişim rehberi", "personel"]],
  ["chat-dots",        ChatDotsIcon,          ["mesaj yazıyor", "bekleniyor", "chat"]],
  ["chat-text",        ChatTextIcon,          ["metin mesajı", "sms", "yazışma"]],
  ["chats",            ChatsIcon,             ["sohbetler", "mesajlar", "iletişimler"]],
  ["whatsapp",         WhatsappLogoIcon,      ["whatsapp", "mesaj", "anlık ileti"]],
  ["telegram",         TelegramLogoIcon,      ["telegram", "mesaj", "kanal"]],

  // ── Kullanıcı & Güvenlik ───────────────────────────────────────────────────
  ["user",             UserIcon,              ["kullanıcı", "kişi", "öğrenci", "personel"]],
  ["users",            UsersIcon,             ["kullanıcılar", "grup", "topluluk", "ekip", "bölüm"]],
  ["user-check",       UserCheckIcon,         ["onaylı kullanıcı", "kayıtlı öğrenci", "kabul"]],
  ["user-plus",        UserPlusIcon,          ["kayıt ol", "yeni öğrenci", "ekle"]],
  ["user-cog",         UserGearIcon,          ["kullanıcı ayarları", "profil", "hesap"]],
  ["shield",           ShieldCheckIcon,       ["güvenlik", "koruma", "onaylı", "akredite"]],
  ["lock",             LockKeyIcon,           ["kilit", "şifre", "güvenli", "erişim kısıtlı"]],
  ["key",              KeyIcon,               ["anahtar", "erişim", "şifre", "giriş"]],
  ["fingerprint",      FingerprintIcon,       ["parmak izi", "kimlik", "biyometrik"]],
  ["id-card",          IdentificationCardIcon, ["kimlik kartı", "öğrenci kartı", "personel kartı"]],
  ["user-circle",      UserCircleIcon,        ["profil resmi", "avatar", "hesap"]],
  ["user-list",        UserListIcon,          ["kullanıcı listesi", "üyeler", "kayıtlılar"]],
  ["users-three",      UsersThreeIcon,        ["üç kişi", "ekip", "grup", "komite"]],
  ["user-focus",       UserFocusIcon,         ["kullanıcı odak", "hedef kitle", "profil"]],
  ["password",         PasswordIcon,          ["şifre", "parola", "güvenlik"]],

  // ── Konum & Kampüs ─────────────────────────────────────────────────────────
  ["map",              MapTrifoldIcon,        ["harita", "kampüs haritası", "konum"]],
  ["map-pin",          MapPinIcon,            ["pin", "adres", "kampüs", "konum işareti"]],
  ["navigation",       NavigationArrowIcon,   ["navigasyon", "yol tarifi", "yön"]],
  ["compass",          CompassIcon,           ["pusula", "yön", "keşfet"]],
  ["bus",              BusIcon,               ["otobüs", "ulaşım", "toplu taşıma", "servis"]],
  ["car",              CarIcon,               ["araba", "araç", "park", "otopark"]],
  ["plane",            AirplaneTiltIcon,      ["uçak", "uluslararası", "havalimanı"]],
  ["building",         BuildingIcon,          ["bina", "fakülte", "enstitü", "blok"]],
  ["buildings",        BuildingsIcon,         ["binalar", "kampüs", "şehir"]],
  ["landmark",         BankIcon,              ["tarihi yapı", "anıt", "simge", "amfi"]],
  ["tree",             TreeIcon,              ["ağaç", "doğa", "kampüs ortamı"]],
  ["park",             ParkIcon,              ["park", "bahçe", "yeşil alan"]],
  ["map-pin-line",     MapPinLineIcon,        ["konum çizgisi", "rota", "adres işareti"]],
  ["path",             PathIcon,              ["yol", "rota", "güzergah"]],
  ["road",             RoadHorizonIcon,       ["yol", "karayolu", "ufuk"]],
  ["train",            TrainIcon,             ["tren", "ray", "ulaşım"]],
  ["taxi",             TaxiIcon,              ["taksi", "ulaşım", "transfer"]],

  // ── Teknoloji & Sistem ─────────────────────────────────────────────────────
  ["database",         DatabaseIcon,          ["veri tabanı", "veri", "sistem", "kayıt"]],
  ["dashboard",        SquaresFourIcon,       ["panel", "kontrol paneli", "özet ekranı"]],
  ["monitor",          MonitorIcon,           ["ekran", "bilgisayar", "masaüstü", "uzaktan erişim"]],
  ["laptop",           LaptopIcon,            ["dizüstü", "bilgisayar"]],
  ["tablet",           DeviceTabletIcon,      ["tablet", "mobil cihaz"]],
  ["smartphone",       DeviceMobileIcon,      ["telefon", "mobil", "akıllı telefon", "uygulama"]],
  ["pie-chart",        ChartPieIcon,          ["pasta grafik", "istatistik", "rapor", "oran"]],
  ["bar-chart",        ChartBarIcon,          ["çubuk grafik", "istatistik", "karşılaştırma"]],
  ["line-chart",       ChartLineIcon,         ["çizgi grafik", "trend", "ilerleme"]],
  ["trending-up",      TrendUpIcon,           ["büyüme", "artış", "gelişme", "başarı trendi"]],
  ["table",            TableIcon,             ["tablo", "veri tablosu", "ders programı"]],
  ["code",             CodeIcon,              ["kod", "yazılım", "programlama", "geliştirme"]],
  ["terminal",         TerminalIcon,          ["terminal", "komut satırı", "yazılım"]],
  ["qr",               QrCodeIcon,            ["qr kod", "barkod", "tara", "hızlı erişim"]],
  ["printer",          PrinterIcon,           ["yazıcı", "yazdır", "belge basmak"]],
  ["server",           HardDrivesIcon,        ["sunucu", "sistem", "altyapı", "hosting"]],
  ["cpu",              CpuIcon,               ["işlemci", "donanım", "teknoloji", "bilişim"]],
  ["hard-drive",       HardDriveIcon,         ["disk", "depolama", "yedek", "dosya sistemi"]],
  ["wifi",             WifiHighIcon,          ["wifi", "internet", "kablosuz ağ", "bağlantı"]],
  ["cloud",            CloudIcon,             ["bulut", "depolama", "online"]],
  ["cloud-upload",     CloudArrowUpIcon,      ["bulut yükleme", "upload", "kaydet"]],
  ["cloud-download",   CloudArrowDownIcon,    ["bulut indirme", "download", "indir"]],
  ["desktop",          DesktopIcon,           ["masaüstü", "bilgisayar", "pc"]],
  ["git",              GitBranchIcon,         ["git", "versiyon", "dal", "geliştirme"]],
  ["robot",            RobotIcon,             ["robot", "yapay zeka", "otomasyon", "bot"]],

  // ── Mali & İdari ───────────────────────────────────────────────────────────
  ["credit-card",      CreditCardIcon,        ["kredi kartı", "ödeme", "burs", "harç"]],
  ["wallet",           WalletIcon,            ["cüzdan", "ödeme", "bütçe"]],
  ["receipt",          ReceiptIcon,           ["makbuz", "dekont", "ödeme belgesi", "fiş"]],
  ["scale",            ScalesIcon,            ["terazi", "hukuk", "adalet", "yönetmelik"]],
  ["money",            MoneyIcon,             ["para", "nakit", "burs", "ödeme", "destek"]],
  ["coins",            CoinsIcon,             ["bozuk para", "ücret", "öğrenim harcı"]],
  ["dollar",           CurrencyDollarIcon,    ["dolar", "ücret", "fiyat", "maliyet"]],
  ["euro",             CurrencyEurIcon,       ["euro", "döviz", "kur"]],
  ["pound",            CurrencyGbpIcon,       ["sterlin", "döviz", "kur"]],
  ["handshake",        HandshakeIcon,         ["el sıkışma", "anlaşma", "iş birliği"]],
  ["briefcase",        BriefcaseIcon,         ["evrak çantası", "iş", "kariyer"]],
  ["stamp",            StampIcon,             ["damga", "mühür", "onay"]],
  ["gavel",            GavelIcon,             ["tokmak", "yargı", "karar", "hukuk"]],

  // ── Takvim & Planlama ──────────────────────────────────────────────────────
  ["calendar",         CalendarIcon,          ["takvim", "tarih", "etkinlik", "program"]],
  ["calendar-blank",   CalendarBlankIcon,     ["boş takvim", "tarih seç", "plan"]],
  ["calendar-check",   CalendarCheckIcon,     ["onaylı randevu", "ders takvimi", "sınav takvimi"]],
  ["calendar-dots",    CalendarDotsIcon,      ["etkinlik takvimi", "özel günler", "program"]],
  ["check-square",     CheckSquareIcon,       ["onay kutusu", "seçim", "tamamlandı"]],
  ["list-checks",      ListChecksIcon,        ["kontrol listesi", "yapılacaklar", "görev"]],
  ["list-bullets",     ListBulletsIcon,       ["madde listesi", "sıralama", "içerik"]],
  ["timer",            TimerIcon,             ["zamanlayıcı", "süre", "geri sayım", "sınav süresi"]],
  ["hourglass",        HourglassIcon,         ["kum saati", "bekleme", "süre", "son başvuru"]],
  ["alarm",            AlarmIcon,             ["alarm", "hatırlatma", "uyandırma"]],
  ["clock-countdown",  ClockCountdownIcon,    ["geri sayım", "süre", "zamanlayıcı"]],

  // ── Medya & Diğer ──────────────────────────────────────────────────────────
  ["download",         DownloadSimpleIcon,    ["indir", "indirme", "dosya indir", "al"]],
  ["upload",           UploadSimpleIcon,      ["yükle", "upload", "dosya yükle"]],
  ["image",            ImageIcon,             ["resim", "fotoğraf", "görsel", "galeri"]],
  ["music",            MusicNoteIcon,         ["müzik", "konser", "kültür sanat", "etkinlik"]],
  ["heart",            HeartIcon,             ["kalp", "favori", "sağlık", "beğeni"]],
  ["stethoscope",      StethoscopeIcon,       ["stetoskop", "sağlık", "tıp", "hastane", "sağlık birimi"]],
  ["umbrella",         UmbrellaIcon,          ["şemsiye", "sigorta", "koruma", "güvence"]],
  ["camera",           CameraIcon,            ["kamera", "fotoğraf", "çekim"]],
  ["play",             PlayIcon,              ["oynat", "video", "başlat"]],
  ["pause",            PauseIcon,             ["duraklat", "beklet", "ara ver"]],
  ["speaker",          SpeakerHighIcon,       ["hoparlör", "ses", "duyuru"]],
  ["microphone",       MicrophoneIcon,        ["mikrofon", "ses kayıt", "podcast"]],
  ["film",             FilmSlateIcon,         ["film", "sinema", "video"]],
  ["palette",          PaletteIcon,           ["palet", "sanat", "tasarım", "renk"]],
  ["paint-brush",      PaintBrushIcon,        ["fırça", "boya", "tasarım"]],
  ["sparkle",          SparkleIcon,           ["parıltı", "yeni", "özel", "premium"]],
  ["sun",              SunIcon,               ["güneş", "aydınlık", "gündüz"]],
  ["moon",             MoonIcon,              ["ay", "gece", "karanlık tema"]],
  ["thumbs-up",        ThumbsUpIcon,          ["beğen", "olumlu", "onay"]],
  ["thumbs-down",      ThumbsDownIcon,        ["beğenme", "olumsuz", "ret"]],
  ["smiley",           SmileyIcon,            ["gülen yüz", "emoji", "mutlu"]],
  ["hand-heart",       HandHeartIcon,         ["yardım", "bağış", "gönüllü"]],
  ["first-aid",        FirstAidIcon,          ["ilk yardım", "acil", "sağlık"]],
  ["pill",             PillIcon,              ["hap", "ilaç", "eczane"]],
  ["thermometer",      ThermometerIcon,       ["termometre", "sıcaklık", "ateş"]],
  ["wheelchair",       WheelchairIcon,        ["tekerlekli sandalye", "engelli", "erişilebilirlik"]],
  ["baby",             BabyIcon,              ["bebek", "çocuk", "kreş"]],
  ["praying",          HandsPrayingIcon,      ["dua", "ibadet", "manevi"]],

  // ── Oklar & Yönlendirme ────────────────────────────────────────────────────
  ["arrow-up",         ArrowUpIcon,           ["yukarı ok", "yüksel", "artan"]],
  ["arrow-down",       ArrowDownIcon,         ["aşağı ok", "düşen", "azalan"]],
  ["expand",           ArrowsOutSimpleIcon,   ["genişlet", "tam ekran", "büyüt"]],
  ["collapse",         ArrowsInSimpleIcon,    ["daralt", "küçült", "simge durumu"]],
  ["caret-down",       CaretDownIcon,         ["açılır menü", "aşağı", "dropdown"]],
  ["caret-up",         CaretUpIcon,           ["yukarı", "kapat", "daralt"]],
  ["caret-left",       CaretLeftIcon,         ["sol", "geri", "önceki"]],

  // ── Düzenleme & Eylem ──────────────────────────────────────────────────────
  ["trash",            TrashIcon,             ["çöp", "sil", "kaldır"]],
  ["copy",             CopyIcon,              ["kopyala", "çoğalt", "yapıştır"]],
  ["plus",             PlusIcon,              ["artı", "ekle", "yeni"]],
  ["minus",            MinusIcon,             ["eksi", "çıkar", "azalt"]],
  ["equals",           EqualsIcon,            ["eşittir", "karşılaştır", "denge"]],
  ["power",            PowerIcon,             ["güç", "aç/kapat", "başlat"]],
  ["export",           ExportIcon,            ["dışa aktar", "paylaş", "gönder"]],
  ["flag-checkered",   FlagCheckeredIcon,     ["bitiş", "hedef", "tamamlandı"]],
  ["lightning",        LightningIcon,         ["yıldırım", "hızlı", "enerji"]],
  ["fire",             FireIcon,              ["ateş", "popüler", "trend", "sıcak"]],
  ["confetti",         ConfettiIcon,          ["konfeti", "kutlama", "başarı"]],
  ["prohibit",         ProhibitIcon,          ["yasak", "engelle", "kısıtla"]],
  ["loading",          CircleNotchIcon,       ["yükleniyor", "bekleme", "işleniyor"]],
  ["spinner",          SpinnerGapIcon,        ["dönen", "yükleniyor", "bekleme"]],
];

// Anahtar → bileşen map'i (render için)
export const ICON_MAP = Object.fromEntries(
  ICON_ENTRIES.map(([k, v]) => [k, v])
) as Record<string, PhosphorIcon>;

// Fallback ikon (bilinmeyen anahtar için)
export { ArrowSquareOutIcon as FallbackIcon } from "@phosphor-icons/react/ssr";